db: 
  image: mongo
  restart: always
  volumes:
    - /var/lib/mongodb:/data/db
  ports:
    - 27017:27017
mqtt:
  image: eclipse-mosquitto
  restart: always
  ports:
    - 1883:1883
proxy: 
  image: jwilder/nginx-proxy 
  ports: 
    - 80:80
  restart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
extract-moves:
  build: extract-moves
  container_name: extract-moves
  links:
    - db:db
    - mqtt:mqtt
  environment:
    - VIRTUAL_HOST=moves-webhook.micahf.com
  env_file:
    - .env
extract-automatic:
  build: extract-automatic
  container_name: extract-automatic
  links:
    - db:db
    - mqtt:mqtt
  environment:
    - VIRTUAL_HOST=automatic.micahf.com
  env_file:
    - .env
days-to-trackpoints:
  build: days-to-trackpoints
  container_name: days-to-trackpoints
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env
elevation:
  build: elevation
  container_name: elevation
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env
auth:
  build: auth
  container_name: auth
  links:
    - db:db
  env_file:
    - .env
  environment:
    - MONGO_URL=mongodb://db/dw
    - PORT=8000
    - VIRTUAL_HOST=oauth.micahf.com,authority-figure.micahf.com

extract-instagram:
  build: extract-instagram
  container_name: extract-instagram
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env  
places:
  build: places
  container_name: places
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env

bearing:
  build: bearing
  container_name: bearing
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env
inhabited:
  build: inhabited
  container_name: inhabited
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env

timezone:
  build: timezone
  container_name: timezone
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env

adp:
  build: adp
  container_name: adp
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env

adp_w2:
  build: adp_w2
  container_name: adp_w2
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env


geocode:
  build: geocode
  container_name: geocode
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env

vehicles:
  build: vehicles
  container_name: vehicles
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env

weather:
  build: weather
  container_name: weather
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env

extract-twitter:
  build: extract-twitter
  container_name: extract-twitter
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env
street-view:
  build: street-view
  container_name: street-view
  links:
    - db:db
    - mqtt:mqtt
  env_file:
    - .env